#!/usr/bin/env python
import os
import shlex
import sys

try: from bt import *
except: from __init__ import *

@task(source = ["README.md", "pyproject.toml", "*.py"], output = "dist")
def build():
	rm("dist")
	sh("python -m build")

@task
def documentation(command = "singlehtml"):
	from sphinx.cmd.build import main
	rm(".documentation")
	sys.stderr = sys.stdout
	main(["-M", command, "documentation", ".documentation"])

@task(build)
def publish(): sh("twine upload -r pypi dist/*")

@task(build)
def publishTest(): sh("twine upload -r testpypi dist/*")

@task
def installEditable(): sh("pip install --user --break-system-packages -e .")

@task(build)
def install(): sh("pip install --user --break-system-packages dist/*.whl")

@task
def uninstall(): sh("pip uninstall --user --break-system-packages buildt")

@task
def download(): sh("pip install --user --break-system-packages --force-reinstall buildt")

@task
def downloadTest(): sh("pip install --user --break-system-packages --force-reinstall -i https://test.pypi.org/project buildt")
