name: deploy

on:
  push:
    branches: ["a"]
  pull_request:
    branches: ["a"]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip

    - run: pip install sphinx furo

    - name: Generate
      run: |
        ./bs documentation
        mv .documentation/singlehtml .pages

    - uses: actions/upload-pages-artifact@v3
      with:
        path: .pages

    - uses: actions/deploy-pages@v4
